baseUrl=http://localhost:8080/api-docs/

app.env=dev

headless=true

#Endpoint
epLogin=/api/v1/auth/login
epRegister=/api/v1/auth/register
epForgotPW=/api/v1/auth/forgot-password
epProfile=/api/v1/users/profile
epJobPost=/api/v1/jobs

#Account
email=duydien3504@gmail.com
password=Abcd1234@