name: Test README.md

on:
  push:
    branches: ["main"]

jobs:
  Thuc_hanh_doc_file:
    runs-on: ubuntu-latest

    steps:
      - name: Bước 1 - Xin chào
        run: echo "Hutech"

      - name: Bước 2 - Tải code
        uses: actions/checkout@v6.0.2

      - name: Bước 3 - Đọc file
        run: cat README.md
